config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'error', to: 'errors#error'
  get 'help', to: 'static_pages#help'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  patch 'cancel/:id', to: 'bikes#cancel', as: 'cancel'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :bikes, except: :destroy
  resources :admins, except: :destroy, module: 'admin'
  resources :calendars, except: %i[show edit update]
  resources :bookings, except: %i[destroy edit]
  resources :booking_statuses, only: :create do
    post 'booking', on: :collection
    post 'cancel', on: :collection
    post 'payment', on: :collection
    post 'finished', on: :collection
  end
  namespace :admin do
    root 'admins#home'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    patch 'approve/:id', to: 'bikes#update', as: 'bikes_approve'
    delete 'destroy/:id', to: 'admins#destroy', as: 'destroy'
    resources :bikes, except: :destroy
    resources :categories
    resources :bookings, only: %i[index show]
    resources :users, only: %i[index show]
  end
end

app/models/bike.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bikes
#
#  id             :bigint           not null, primary key
#  description    :string
#  license_plates :string
#  name           :string
#  price          :float
#  status         :integer          default("pending")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  admin_id       :bigint
#  category_id    :bigint
#  user_id        :bigint
#
# Indexes
#
#  index_bikes_on_admin_id        (admin_id)
#  index_bikes_on_category_id     (category_id)
#  index_bikes_on_license_plates  (license_plates) UNIQUE
#  index_bikes_on_user_id         (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (admin_id => admin_users.id)
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Bike < ApplicationRecord
  has_many :calendars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :admin, optional: true
  has_many_attached :images

  enum status: %i[pending cancel available]

  validates :name, presence: true, format: { with: /\A[a-zA-Z]+-[a-zA-Z]+-\d{4}\z/ }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :license_plates, presence: true, format: { with: /\A\d{2}-[A-Z]{1}\d{1}-\d{5}\z/ }, uniqueness: true

  scope :order_by_newest, -> { order(updated_at: :desc) }
  scope :find_by_status_available_correct_user, lambda { |current_user|
                                                  where(status: 'available', user_id: current_user.id)
                                                }
  scope :filter_by_name_or_license_plates, lambda { |params_filter|
                                             if params_filter.present?
                                               where('name LIKE ? OR license_plates LIKE ?', "%#{params_filter}%", "%#{params_filter}%")
                                             end
                                           }
  scope :filter_by_category, ->(params_category) { where(category_id: params_category) if params_category.present? }
  scope :filter_by_status, ->(params_status) { where(status: params_status) if params_status.present? }
  scope :filter_by_start_day_end_day, lambda { |start_day, end_day|
                                        joins(:calendars).where('calendars.start_day <= ? AND calendars.end_day >= ? AND ? <= ? AND ? >= ?', start_day, end_day, start_day, end_day, start_day, Time.now)
                                      }
end

app/controllers/admin/bikes_controller.rb
# frozen_string_literal: true

module Admin
  class BikesController < Admin::ApplicationController
    before_action :logged_in_admin
    before_action :load_category, only: :index
    before_action :load_status, only: :index
    before_action :load_booking, only: :show
    before_action :load_calendar, only: :show
    layout :admin_layout

    def index
      @bikes = Bike.order_by_newest.filter_by_name_or_license_plates(params[:filter])
                   .filter_by_category(params[:category_id])
                   .filter_by_status(params[:status])
                   .includes(:category, :user).page params[:page]
    end

    def show
      @bike = Bike.find(params[:id])
    end

    def update
      @bike = Bike.find(params[:id])
      if @bike.update(status: 2, admin_id: current_admin.id)
        flash[:success] = 'Bike was approved.'
        redirect_to admin_bikes_path, status: 303
      else
        flash.now[:danger] = 'Bike was not approved.'
        render :show, status: 303
      end
    end

    private

    def load_category
      @categories = Category.all
    end

    def load_status
      @status = Bike.statuses
    end

    def load_booking
      @bookings = Booking.where(bike_id: params[:id]).order_by_newest.includes(:user, bike: :user).page(params[:page])
    end

    def load_calendar
      @calendars = Calendar.where(bike_id: params[:id]).includes(:bike).page(params[:page])
    end
  end
end

app/controllers/bikes_controller.rb
# frozen_string_literal: true

class BikesController < ApplicationController
  before_action :logged_in_user
  before_action :load_category, except: %i[show cancel]
  before_action :load_status, only: :index
  before_action :available_bike, only: %i[edit update]
  before_action :correct_bike, only: %i[show cancel]
  before_action :user_lessor?, only: %i[new create index]
  layout :user_layout

  def index
    @bikes = Bike.order_by_newest.where(user_id: current_user.id)
                 .filter_by_name_or_license_plates(params[:filter])
                 .filter_by_category(params[:category_id])
                 .filter_by_status(params[:status])
                 .includes(:category).page params[:page]
  end

  def show; end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user_id = current_user.id
    if @bike.save
      flash[:success] = 'Add new bike successfully.'
      redirect_to bikes_path, status: 303
    else
      render :new, status: 303
    end
  end

  def edit; end

  def update
    if @bike.update(update_params)
      flash[:success] = 'Bike profile updated'
      redirect_to @bike
    else
      render :edit, status: 303
    end
  end

  def cancel
    if @bike.cancel!
      flash[:success] = 'Bike was cancel.'
      redirect_to bike_path, status: 303
    else
      flash.now[:danger] = 'Bike can not cancel.'
      render :show, status: 303
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :category_id, :price, :description, :license_plates, images: [])
  end

  def update_params
    params.require(:bike).permit(:description, images: [])
  end

  def load_category
    @categories = Category.all
  end

  def load_status
    @status = Bike.statuses
  end

  def correct_bike
    @bike = Bike.where(user_id: current_user.id).find(params[:id])
  end

  def available_bike
    @bike = Bike.where(user_id: current_user.id, status: 2).find(params[:id])
  end
end

app/helpers/admin/bikes_helper.rb
# frozen_string_literal: true

module Admin
  module BikesHelper
  end
end

app/helpers/bikes_helper.rb
# frozen_string_literal: true

module BikesHelper
end

app/views/admin/bikes/index.html.erb
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item"><%= link_to 'Bikes', admin_bikes_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="page">List Bikes</li>
      </ol>
    </nav>
  </div>
</div>
<%= render 'layouts/message' %>
<%= form_with url: admin_bikes_path, method: :get, class: "row row-cols-lg-auto g-3 align-items-center" do |form| %>
  <div class="col-12">
    <div class="input-group">
      <%= form.text_field :filter, value: params[:filter], class: 'form-control', placeholder: "Filter" %>
    </div>
  </div>
  <div class="col-12">
    <%= form.collection_select :category_id, @categories, :id, :name, { prompt: '--Category--' }, { class: "form-select" } %>
  </div>
  <div class="col-12">
    <%= form.select :status, @status, { prompt: '--Status--' }, { class: "form-select" } %>
  </div>
  <div class="col-12">
    <%= form.submit "Filter", class: "btn btn-primary" %>
  </div>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">License Plates</th>
      <th scope="col">Lessor</th>
      <th scope="col">Image</th>
      <th scope="col">Price</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @bikes.each do |bike| %>
    <tr>
      <th scope="row"><%= bike.id %></th>
      <td><%= bike.name %></td>
      <td><%= bike.license_plates %></td>
      <td><%= bike.user.name %></td>
      <td><%= bike.images.first.present? ? image_tag(bike.images.first, style:"width:100px; height:100px") : image_tag("bike_default.png", style:"width:100px; height:100px") %></td>
      <td><%= bike.price %></td>
      <td><%= bike.category.name %></td>
      <td><%= bike.status %></td>
      <td>
        <%= link_to '', admin_bike_path(bike.id), class: "bi bi-search" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @bikes, window: 2, theme: 'bootstrap-5',
                                pagination_class: "d-flex justify-content-center" %>

app/views/admin/bikes/show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item"><%= link_to 'Bikes', admin_bikes_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item active" aria-current="page">Show Bike</li>
          </ol>
        </nav>
      </div>
    </div>
    <%= render 'layouts/message' %>
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <h5 class="my-3">Images</h5>
            <% @bike.images.each do |image| %>
              <%= image_tag image, style:"width:100px; height:100px" %>
            <% end %>
            <div class="d-flex justify-content-center my-4">
              <%= link_to_if @bike.pending?, 'Approve', admin_bikes_approve_path(@bike.id), data: { turbo_method: :patch }, class: "btn btn-outline-primary ms-1" %>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <h5 class="text-center p-3">Calendar</h5>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Start Day</th>
                  <th scope="col">End Day</th>
                </tr>
              </thead>
              <tbody>
                <% @bike.calendars.each do |calendar| %>
                  <tr>
                    <td><%= calendar.id %></td>
                    <td><%= calendar.start_day %></td>
                    <td><%= calendar.end_day %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">License Plates</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.license_plates %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Price</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.price %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Status</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.status %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Category</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.category.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">User</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.user.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Description</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.description %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Approver</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @bike.admin.nil? ? '' : @bike.admin.name %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<h5 class='text-center display-5 text-info'>History</h5>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Bike</th>
      <th scope="col">License Plates</th>
      <th scope="col">Renter</th>
      <th scope="col">Lessor</th>
      <th scope="col">Status</th>
      <th scope="col">Start Day</th>
      <th scope="col">End Day</th>
      <th scope="col">Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <th scope="row"><%= booking.id %></th>
        <td><%= booking.bike.name %></td>
        <td><%= booking.bike.license_plates %></td>
        <td><%= booking.user.name %></td>
        <td><%= booking.bike.user.name %></td>
        <td><%= booking.status %></td>
        <td><%= booking.booking_start_day %></td>
        <td><%= booking.booking_end_day %></td>
        <td><%= total_price(booking) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @bookings, window: 2, theme: 'bootstrap-5',
                                pagination_class: "d-flex justify-content-center" %>