config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'error', to: 'errors#error'
  get 'help', to: 'static_pages#help'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  patch 'cancel/:id', to: 'bikes#cancel', as: 'cancel'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :bikes, except: :destroy
  resources :admins, except: :destroy, module: 'admin'
  resources :calendars, except: %i[show edit update]
  resources :bookings, except: %i[destroy edit]
  resources :booking_statuses, only: :create do
    post 'booking', on: :collection
    post 'cancel', on: :collection
    post 'payment', on: :collection
    post 'finished', on: :collection
  end
  namespace :admin do
    root 'admins#home'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    patch 'approve/:id', to: 'bikes#update', as: 'bikes_approve'
    delete 'destroy/:id', to: 'admins#destroy', as: 'destroy'
    resources :bikes, except: :destroy
    resources :categories
    resources :bookings, only: %i[index show]
    resources :users, only: %i[index show]
  end
end

app/views/admin/admins/edit.html.erb
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item"><%= link_to 'Admins', admins_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Profile</li>
      </ol>
    </nav>
  </div>
</div>

<div class="container">
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-6" style="min-height: 490px">
      <%= form_with model: @admin do |f| %>
        <div class="mb-4">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:name).first %></div>
        </div>

        <div class="mb-4">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:email).first %></div>
        </div>

        <div class="mb-4">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:password).first %></div>
        </div>

        <div class="mb-4">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:password_confirmation).first %></div>
        </div>

        <div class="d-flex justify-content-around align-items-center">
          <%= f.submit "Update Admin", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/admins/home.html.erb
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="page">Statistics</li>
      </ol>
    </nav>
  </div>
</div>

<%= render 'layouts/message' %>

<canvas id="lineChart"></canvas>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  var ctxL = document.getElementById("lineChart").getContext('2d');
  var myLineChart = new Chart(ctxL, {
    type: 'line',
    data: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      datasets: [{
        label: "My First dataset",
        data: [65, 59, 80, 81, 56, 55, 40],
        backgroundColor: [
          'rgba(105, 0, 132, .2)',
        ],
        borderColor: [
          'rgba(200, 99, 132, .7)',
        ],
        borderWidth: 2
      },
      {
        label: "My Second dataset",
        data: [28, 48, 40, 19, 86, 27, 90],
        backgroundColor: [
          'rgba(0, 137, 132, .2)',
        ],
        borderColor: [
          'rgba(0, 10, 130, .7)',
        ],
        borderWidth: 2
      }
      ]
    },
    options: {
      responsive: true
    }
  });
</script>

app/views/admin/admins/index.html.erb
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item"><%= link_to 'Admins', admins_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="page">List Admins</li>
      </ol>
    </nav>
  </div>
</div>

<%= render 'layouts/message' %>
<%= form_with url: admins_path, method: :get, class: "row row-cols-lg-auto g-3 align-items-center" do |form| %>
  <div class="col-12">
    <div class="input-group">
      <%= form.text_field :filter, value: params[:filter], class: 'form-control', placeholder: "Filter" %>
    </div>
  </div>
  <div class="col-12">
    <%= form.submit "Filter", class: "btn btn-primary" %>
  </div>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @admins.each do |admin| %>
    <tr>
      <th scope="row"><%= admin.id %></th>
      <td><%= admin.name %></td>
      <td><%= admin.email %></td>
      <td>
        <%= link_to '', admin_path(admin.id), class: "bi bi-search" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @admins, window: 2, theme: 'bootstrap-5',
                                pagination_class: "d-flex justify-content-center" %>

app/views/admin/admins/new.html.erb
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item"><%= link_to 'Admins', admins_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="page">New Admin</li>
      </ol>
    </nav>
  </div>
</div>

<div class="container">
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-6" style="min-height: 490px">
      <%= form_with model: @admin do |f| %>
        <div class="mb-4">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:name).first %></div>
        </div>

        <div class="mb-4">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:email).first %></div>
        </div>

        <div class="mb-4">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:password).first %></div>
        </div>

        <div class="mb-4">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
          <div class="form-text text-danger"><%= @admin.errors.full_messages_for(:password_confirmation).first %></div>
        </div>

        <div class="d-flex justify-content-around align-items-center">
          <%= f.submit "New Admin", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/admins/show.html.erb
<%= render 'layouts/message' %>
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item"><%= link_to 'Admins', admins_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item active" aria-current="page">Admin Profile</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <h5 class="my-3">Action</h5>
            <%= image_tag 'logo.png', style:"width:100px; height:100px" %>
            <div class="d-flex justify-content-center my-4">
              <%= link_to 'Edit', edit_admin_path(@admin.id), class: "btn btn-outline-info ms-1" %>
              <%= link_to 'Delete', admin_destroy_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger ms-1" %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @admin.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @admin.email %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>