config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'error', to: 'errors#error'
  get 'help', to: 'static_pages#help'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  patch 'cancel/:id', to: 'bikes#cancel', as: 'cancel'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :bikes, except: :destroy
  resources :admins, except: :destroy, module: 'admin'
  resources :calendars, except: %i[show edit update]
  resources :bookings, except: %i[destroy edit]
  resources :booking_statuses, only: :create do
    post 'booking', on: :collection
    post 'cancel', on: :collection
    post 'payment', on: :collection
    post 'finished', on: :collection
  end
  namespace :admin do
    root 'admins#home'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    patch 'approve/:id', to: 'bikes#update', as: 'bikes_approve'
    delete 'destroy/:id', to: 'admins#destroy', as: 'destroy'
    resources :bikes, except: :destroy
    resources :categories
    resources :bookings, only: %i[index show]
    resources :users, only: %i[index show]
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                :bigint           not null, primary key
#  activated_at      :datetime
#  activation_digest :string
#  address           :string
#  email             :string
#  name              :string
#  password_digest   :string
#  phone_number      :string
#  remember_digest   :string
#  reset_digest      :string
#  reset_sent_at     :datetime
#  role              :integer          default("renter")
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  has_one_attached :avatar
  has_many :bikes, dependent: :destroy
  has_many :bookings, dependent: :destroy

  before_save   :downcase_email
  before_create :create_activation_digest

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i

  enum role: %i[renter lessor]

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  scope :order_by_newest, -> { order(updated_at: :desc) }
  scope :filter_by_name_or_email, lambda { |params_filter|
                                    if params_filter.present?
                                      where('name LIKE ? OR email LIKE ?', "%#{params_filter}%", "%#{params_filter}%")
                                    end
                                  }

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost:)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def activated?
    activated_at.present?
  end

  def activate
    update_columns(activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    before_action :logged_in_admin
    layout :admin_layout

    def index
      @users = User.filter_by_name_or_email(params[:filter]).order_by_newest.page params[:page]
    end

    def show
      @user = User.find(params[:id])
      if @user.renter?
        @bookings = Booking.where(user_id: params[:id]).page params[:page]
        render action: 'renter_show'
      else
        @bikes = Bike.where(user_id: params[:id]).page params[:page]
        render action: 'lessor_show'
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[show edit update]
  before_action :correct_user, only: %i[edit update]
  before_action :load_user, only: %i[show edit update]
  layout :user_layout, only: %i[show edit]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_url, status: 303
    else
      render :new, status: 422
    end
  end

  def edit; end

  def update
    if @user.update(update_params)
      flash[:success] = 'User profile updated'
      redirect_to @user
    else
      render :edit, status: 303
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def load_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :phone_number,
                                 :avatar)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to error_path, status: 303 unless current_user?(@user)
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item"><%= link_to 'Users', admin_users_path, class: "text-decoration-none" %></li>
        <li class="breadcrumb-item active" aria-current="page">List User</li>
      </ol>
    </nav>
  </div>
</div>

<%= render 'layouts/message' %>

<%= form_with url: admin_users_path, method: :get, class: "row row-cols-lg-auto g-3 align-items-center" do |form| %>
  <div class="col-12">
    <div class="input-group">
      <%= form.text_field :filter, value: params[:filter], class: 'form-control', placeholder: "Filter" %>
    </div>
  </div>
  <div class="col-12">
    <%= form.submit "Filter", class: "btn btn-primary" %>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td>
        <%= link_to '', admin_user_path(user.id), class: "bi bi-search" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @users, window: 2, theme: 'bootstrap-5',
                                pagination_class: "d-flex justify-content-center" %>

app/views/admin/users/lessor_show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item"><%= link_to 'Users', admin_users_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item active" aria-current="page">Lessor Profile</li>
          </ol>
        </nav>
      </div>
    </div>
    <%= render 'layouts/message' %>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <h5 class="my-3">Avatar</h5>
            <%= @user.avatar.present? ? image_tag(@user.avatar, style:"width:100px; height:100px") : image_tag("avatar_default.jpg", style:"width:100px; height:100px") %>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.address %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone Number</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.phone_number %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<h5 class='text-center display-5 text-info'>List Bike</h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">License Plates</th>
      <th scope="col">Lessor</th>
      <th scope="col">Image</th>
      <th scope="col">Price</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @bikes.each do |bike| %>
    <tr>
      <th scope="row"><%= bike.id %></th>
      <td><%= bike.name %></td>
      <td><%= bike.license_plates %></td>
      <td><%= bike.user.name %></td>
      <td><%= bike.images.first.present? ? image_tag(bike.images.first, style:"width:100px; height:100px") : image_tag("bike_default.png", style:"width:100px; height:100px") %></td>
      <td><%= bike.price %></td>
      <td><%= bike.category.name %></td>
      <td><%= bike.status %></td>
      <td>
        <%= link_to '', admin_bike_path(bike.id), class: "bi bi-search" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @bikes, window: 2, theme: 'bootstrap-5',
                                pagination_class: "d-flex justify-content-center" %>

app/views/admin/users/renter_show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><%= link_to 'Home', admin_root_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item"><%= link_to 'Users', admin_users_path, class: "text-decoration-none" %></li>
            <li class="breadcrumb-item active" aria-current="page">Renter Profile</li>
          </ol>
        </nav>
      </div>
    </div>
    <%= render 'layouts/message' %>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <h5 class="my-3">Avatar</h5>
            <%= @user.avatar.present? ? image_tag(@user.avatar, style:"width:100px; height:100px") : image_tag("avatar_default.jpg", style:"width:100px; height:100px") %>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.address %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone Number</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.phone_number %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<h5 class='text-center display-5 text-info'>List Booking</h5>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Bike</th>
      <th scope="col">License Plates</th>
      <th scope="col">Lessor</th>
      <th scope="col">Status</th>
      <th scope="col">Start Day</th>
      <th scope="col">End Day</th>
      <th scope="col">Total Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <th scope="row"><%= booking.id %></th>
        <td><%= booking.bike.name %></td>
        <td><%= booking.bike.license_plates %></td>
        <td><%= booking.bike.user.name %></td>
        <td><%= booking.status %></td>
        <td><%= booking.booking_start_day %></td>
        <td><%= booking.booking_end_day %></td>
        <td><%= total_price(booking) %></td>
        <td>
          <%= link_to '', admin_booking_path(booking.id), class: "bi bi-search" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @bookings, window: 2, theme: 'bootstrap-5',
                                pagination_class: "d-flex justify-content-center" %>