config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get 'error', to: 'errors#error'
  get 'help', to: 'static_pages#help'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  patch 'cancel/:id', to: 'bikes#cancel', as: 'cancel'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :bikes, except: :destroy
  resources :admins, except: :destroy, module: 'admin'
  resources :calendars, except: %i[show edit update]
  resources :bookings, except: %i[destroy edit]
  resources :booking_statuses, only: :create do
    post 'booking', on: :collection
    post 'cancel', on: :collection
    post 'payment', on: :collection
    post 'finished', on: :collection
  end
  namespace :admin do
    root 'admins#home'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    patch 'approve/:id', to: 'bikes#update', as: 'bikes_approve'
    delete 'destroy/:id', to: 'admins#destroy', as: 'destroy'
    resources :bikes, except: :destroy
    resources :categories
    resources :bookings, only: %i[index show]
    resources :users, only: %i[index show]
  end
end

app/views/layouts/_admin_sidebar.html.erb
<div class="row w-100"> 
  <div class="col-2 bg-light h-100" style="min-height: 930px">
    <div class="row justify-content-center items-align-center text-center" style="min-height: 200px">
      <%= image_tag "logo.png", class:"h-100 w-100 rounded-circle mt-3", style:"max-height: 200px; max-width: 200px" %>
      <%= link_to current_admin.name, current_admin, class: "nav-link link-dark px-2 bi bi-person" %>
    </div>
    <hr>
    <ul class="list-unstyled ps-0 mx-5">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#category-collapse" aria-expanded="false">
          <i class="bi bi-journal-check"></i> Categories
        </button>
        <div class="collapse" id="category-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'New Category', new_admin_category_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
            <li><%= link_to 'List Categories', admin_categories_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#user-collapse" aria-expanded="false">
          <i class="bi bi-person"></i> Users
        </button>
        <div class="collapse" id="user-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List User', admin_users_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#bike-collapse" aria-expanded="false">
          <i class="bi bi-bicycle"></i> Bikes
        </button>
        <div class="collapse" id="bike-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List Bike', admin_bikes_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#booking-collapse" aria-expanded="false">
          <i class="bi bi-bookmark-star"></i> Bookings
        </button>
        <div class="collapse" id="booking-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List Booking', admin_bookings_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
    </ul>
      
  </div>
  <div class="col-10">
    <header class="py-1 border-bottom bg-light">
      <div class="container d-flex justify-content-end">
        <ul class="nav">
          <li><%= link_to " Log out", admin_logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "nav-link link-dark bi bi-box-arrow-right" %></li>
        </ul>
      </div>
    </header>
    <%= yield %> 
    <%= render 'layouts/footer' %>
  </div>

app/views/layouts/_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
<link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.css' rel='stylesheet' />
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.0/main.min.js'></script>
<script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center pt-4 my-4 border-top">
  <p class="col-md-4 mb-0 text-muted px-5">© 2021 Company, Inc</p>

  <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-md-0 me-md-auto link-dark text-decoration-none">
    <%= image_tag "logo.png", style: "height: 100px" %>
  </a>

  <ul class="nav col-md-4 justify-content-end px-5">
    <li class="nav-item"><a href="#" class="nav-link link-dark px-2 bi bi-phone-vibrate"> 0808083508</a></li>
    <li class="nav-item"><a href="#" class="nav-link link-dark px-2 bi bi-envelope"> th.rent.bike@gmail.com</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="py-2 bg-light fixed-top border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item">
        <%= link_to ' Home', root_path, class: "nav-link link-dark px-2 active bi bi-house-door" %>
      </li>
      <li class="nav-item"><a href="#" class="nav-link link-dark px-2 bi bi-messenger"> Facebook</a></li>
      <li class="nav-item">
        <%= link_to ' Guide', help_path, class: "nav-link link-dark px-2 bi bi-info-circle" %>
      </li>
    </ul>
    <ul class="nav">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle link-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
            <li><%= link_to "Settings", '#', class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Log out", logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to ' Login', login_path, class: "nav-link link-dark px-2 bi bi-box-arrow-in-right" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_lessor_sidebar.html.erb
<div class="row w-100"> 
  <div class="col-2 bg-light h-100" style="min-height: 930px">
    <div class="row justify-content-center items-align-center text-center" style="min-height: 200px">
      <%= current_user.avatar.present? ? image_tag(current_user.avatar, class:"h-100 w-100 rounded-circle mt-3", style:"max-height: 200px; max-width: 200px") : image_tag("avatar_default.jpg", class:"h-100 w-100 rounded-circle mt-3", style:"max-height: 200px; max-width: 200px") %>
      <%= link_to current_user.name, current_user, class: "nav-link link-dark px-2 bi bi-person" %>
    </div>
    <hr>
    <ul class="list-unstyled ps-0 mx-5">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#bikes-collapse" aria-expanded="false">
          <i class="bi bi-bicycle"></i> Bikes
        </button>
        <div class="collapse" id="bikes-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'Add Bike', new_bike_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
            <li><%= link_to 'List Bikes', bikes_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#calendar-collapse" aria-expanded="false">
          <i class="bi bi bi-calendar"></i> Calendars
        </button>
        <div class="collapse" id="calendar-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'Add time', new_calendar_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
            <li><%= link_to 'Calendar', calendars_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#booking-collapse" aria-expanded="false">
          <i class="bi bi-bookmark-star"></i> Bookings
        </button>
        <div class="collapse" id="booking-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List Booking', bookings_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
  <div class="col-10">
    <header class="py-1 border-bottom bg-light">
      <div class="container d-flex justify-content-end align-items-center">
        <ul class="nav">
          <li><%= link_to " Log out", logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "nav-link link-dark bi bi-box-arrow-right" %></li>
        </ul>
      </div>
    </header>
    <%= yield %> 
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/layouts/_message.html.erb
<div class="container mt-5 pt-2">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
</div>

app/views/layouts/_renter_sidebar.html.erb
<div class="row w-100"> 
  <div class="col-2 bg-light h-100" style="min-height: 930px">
    <div class="row justify-content-center items-align-center text-center" style="min-height: 200px">
      <%= current_user.avatar.present? ? image_tag(current_user.avatar, class:"h-100 w-100 rounded-circle mt-3", style:"max-height: 200px; max-width: 200px") : image_tag("avatar_default.jpg", class:"h-100 w-100 rounded-circle mt-3", style:"max-height: 200px; max-width: 200px") %>
      <%= link_to current_user.name, current_user, class: "nav-link link-dark px-2 bi bi-person" %>
    </div>
    <hr>
    <ul class="list-unstyled ps-0 mx-5">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#booking-collapse" aria-expanded="false">
          <i class="bi bi-bookmark-star"></i> Bookings
        </button>
        <div class="collapse" id="booking-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'New Booking', new_booking_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
            <li><%= link_to 'List Booking', bookings_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
  <div class="col-10">
    <header class="py-1 border-bottom bg-light">
      <div class="container d-flex justify-content-end align-items-center">
        <ul class="nav">
          <li><%= link_to " Log out", logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "nav-link link-dark bi bi-box-arrow-right" %></li>
        </ul>
      </div>
    </header>
    <%= yield %> 
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/layouts/_root_sidebar.html.erb
<div class="row w-100"> 
  <div class="col-2 bg-light h-100" style="min-height: 930px">
    <div class="row justify-content-center items-align-center text-center" style="min-height: 200px">
      <%= image_tag "logo.png", class:"h-100 w-100 rounded-circle mt-3", style:"max-height: 200px; max-width: 200px" %>
      <%= link_to current_admin.name, admin_root_path, class: "nav-link link-dark px-2 bi bi-person" %>
    </div>
    <hr>
    <ul class="list-unstyled ps-0 mx-5">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#admin-collapse" aria-expanded="false">
          <i class="bi bi-person-check"></i> Admins
        </button>
        <div class="collapse" id="admin-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'New Admin', new_admin_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
            <li><%= link_to 'List Admins', admins_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#category-collapse" aria-expanded="false">
          <i class="bi bi-journal-check"></i> Categories
        </button>
        <div class="collapse" id="category-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'New Category', new_admin_category_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
            <li><%= link_to 'List Categories', admin_categories_path, class: "bi bi-dot nav-link link-dark rounded" %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#user-collapse" aria-expanded="false">
          <i class="bi bi-person"></i> User
        </button>
        <div class="collapse" id="user-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List User', admin_users_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#bike-collapse" aria-expanded="false">
          <i class="bi bi-bicycle"></i> Bikes
        </button>
        <div class="collapse" id="bike-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List Bike', admin_bikes_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#booking-collapse" aria-expanded="false">
          <i class="bi bi-bookmark-star"></i> Bookings
        </button>
        <div class="collapse" id="booking-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><%= link_to 'List Booking', admin_bookings_path, class: "bi bi-dot nav-link link-dark rounded " %></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
  <div class="col-10">
    <header class="py-1 border-bottom bg-light">
      <div class="container d-flex justify-content-end">
        <ul class="nav">
          <li><%= link_to " Log out", admin_logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "nav-link link-dark bi bi-box-arrow-right" %></li>
        </ul>
      </div>
    </header>
    <%= yield %> 
    <%= render 'layouts/footer' %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="row"> 
  <div class="col-2 flex-column bg-secondary p-3" style="min-height: 950px">
    <div class="row justify-content-center items-align-center" style="min-height: 200px; background-color: gray">
      <%= image_tag "xe_so.jpg", class: "h-100 w-100 rounded-circle mt-3", style: "max-height: 200px; max-width: 200px" %>
      <p class="text-center">THow</p>
    </div>
  
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link link-dark" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
  </div>
  <div class="col-10">
   <div class="row">
    <header class="py-1 border-bottom">
    <div class="container d-flex flex-wrap justify-content-center align-items-center">
      <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
        <%= image_tag "logo.png", class: "w-50" %>
      </a>
      <ul class="nav">
      <% if logged_in? %>
      <li><%= link_to "Users", '#', class: "nav-link link-dark px-2 " %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle link-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Profile", '#', class: "dropdown-item" %></li>
            <li><%= link_to "Settings", '#', class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Log out", logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to ' Login', login_path, class: "nav-link link-dark px-2 bi bi-box-arrow-in-right" %>
        </li>
      <% end %>
    </ul>
    </div>
    </header>
    </div>
    <div class="row">
      <%= render 'layouts/message' %>
    </div>
    <div class="row">
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/admin_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBike</title>
    <%= render 'layouts/default' %>
  </head>

  <body>
    <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/admin_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBike</title>
    <%= render 'layouts/default' %>
  </head>

  <body>
    <%= render 'layouts/admin_sidebar' %>
  </body>
</html>

app/views/layouts/lessor_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBike</title>
    <%= render 'layouts/default' %>
  </head>

  <body>
    <%= render 'layouts/sidebar' %>
  </body>
</html>

app/views/layouts/renter_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBike</title>
    <%= render 'layouts/default' %>
  </head>

  <body>
    <%= render 'layouts/renter_sidebar' %>
  </body>
</html>

app/views/layouts/root_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentBike</title>
    <%= render 'layouts/default' %>
  </head>

  <body>
    <%= render 'layouts/root_sidebar' %>
  </body>
</html>